#!/bin/bash
set -e
if [[ $TRAVIS_PYTHON_VERSION ]]; then
    VERSION=$TRAVIS_PYTHON_VERSION
else
    VERSION=$(python3 -c 'import sys; v = sys.version_info; print("{}.{}".format(v[0], v[1]));')
fi
flake8 powebscr tests
if [ $VERSION = '3.5' ]; then
    import-order powebscr
else
    echo "Don't check import order with this python version."
fi
